kind: pipeline
type: docker
name: Test on Linux (ARM64)

platform:
  os: linux
  arch: arm64

steps:
  - name: Test
    image: rust
    commands:
      - apt update && apt-get install libhtml-parser-perl -y
      - make test
  - name: Bundle artifact
    image: alpine
    commands:
      - apk add zip
      - >
        zip -j aarch64-unknown-linux-gnu-builds.zip
        target/debug/skyd target/debug/skysh target/debug/sky-bench
  - name: Upload artifacts
    image: plugins/s3
    settings:
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      bucket: everycommit
      source: aarch64-unknown-linux-gnu-builds.zip
      target: ${DRONE_COMMIT}
      path_style: true
      endpoint:
        from_secret: storage_s3_url

---
kind: pipeline
type: docker
name: Test on Linux (x86_64)

steps:
  - name: Test
    image: rust
    commands:
      - apt update && apt-get install libhtml-parser-perl -y
      - make test
