# The current drawback of this workflow is that it doesn't cache artifacts

kind: pipeline
type: ssh
name: Run tests on M1

server:
  host:
    from_secret: host
  user:
    from_secret: user
  password:
    from_secret: password

steps:
- name: Update rust
  commands:
    - /usr/local/bin/rustup-update
- name: Run tests
  environment:
    SRCENV:
      from_secret: srcenv
  commands:
    - source $SRCENV/.cargo/env
    - export RUSTUP_HOME=$SRCENV/.rustup
    - cargo test --verbose
