kind: pipeline
name: Build and Test

steps:
  - name: run-tests
    image: rust
    commands:
      - cargo build --verbose
      - cargo test --verbose

---
kind: pipeline
type: docker
name: Docker Image

steps:
  - name: Push to Docker Hub
    image: plugins/docker
    settings:
      repo: terrabasedb/tdb
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
