[workspace]
resolver = "2"
members = [
    "cli",
    "server",
    "libsky",
    "sky-bench",
    "sky-macros",
    "libstress",
    "stress-test",
    "sky-migrate",
    "harness",
]

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
strip = "debuginfo"
