[package]
name = "tsh"
version = "0.3.2"
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
corelib = {path = "../corelib"}
tokio = {version = "0.2.22", features = ["full"]}
rand = "0.7.3"
devtimer = "4.0.0"
bytes = "0.5.6"

[[bin]]
path="src/bin/benchmark.rs"
name = "tdb-bench"
version = "0.1.0"