[package]
name = "terrabase"
version = "0.1.0"
authors = ["Sayan Nandan <nandansayan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.21", features = ["full"] }
# Import `libcore` which contains code for terrapipe and other utils
libcore = {path="../libcore"}
bytes = "0.5.5"