[package]
name = "tdb"
version = "0.4.4"
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.22", features = ["full"] }
bytes = "0.5.6"
libtdb = {path ="../libtdb"}
bincode = "1.3.1"
parking_lot = "0.11.0"
lazy_static = "1.4.0"
serde_derive = "1.0.116"
serde = {version = "1.0.116", features= ["derive"]}
toml = "0.5.6"
clap = {version = "2.33.3", features=["yaml"]}
env_logger = "0.7.1"
log = "0.4.11"
chrono = "0.4.19"
regex = "1.3.9"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = "0.3.2"

[dev-dependencies]
tokio = { version = "0.2", features = ["test-util"] }