[package]
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
build = "build.rs"
edition = "2021"
name = "skyd"
version = "0.8.0"

[dependencies]
# internal deps
libsky = { path = "../libsky" }
sky_macros = { path = "../sky-macros" }
rcrypt = "0.4.0"
# external deps
ahash = "0.8.3"
bytes = "1.4.0"
chrono = "0.4.24"
clap = { version = "2", features = ["yaml"] }
env_logger = "0.10.0"
hashbrown = { version = "0.13.2", features = ["raw"] }
log = "0.4.17"
openssl = { version = "0.10.52", features = ["vendored"] }
crossbeam-epoch = { version = "0.9.14" }
parking_lot = "0.12.1"
regex = "1.6.0"
serde = { version = "1.0.163", features = ["derive"] }
tokio = { version = "1.28.1", features = ["full"] }
tokio-openssl = "0.6.3"
toml = "0.7.4"
base64 = "0.21.2"
uuid = { version = "1.3.3", features = ["v4", "fast-rng", "macro-diagnostics"] }
crc = "3.0.1"

[target.'cfg(all(not(target_env = "msvc"), not(miri)))'.dependencies]
# external deps
jemallocator = "0.5.0"
[target.'cfg(target_os = "windows")'.dependencies]
# external deps
winapi = { version = "0.3.9", features = ["fileapi"] }

[target.'cfg(unix)'.dependencies]
# external deps
libc = "0.2.144"

[target.'cfg(unix)'.build-dependencies]
# external deps
cc = "1.0.79"

[dev-dependencies]
# internal deps
libstress = { path = "../libstress" }
skytable = { git = "https://github.com/skytable/client-rust", features = [
  "aio",
  "aio-ssl",
], default-features = false, branch = "next" }
# external deps
bincode = "1.3.3"
rand = "0.8.5"
tokio = { version = "1.28.1", features = ["test-util"] }

[features]
nightly = []
persist-suite = []

[package.metadata.deb]
name = "skytable"
maintainer = "Sayan Nandan <nandansayan@outlook.com>"
copyright = "2022, Sayan Nandan <nandansayan@outlook.com>"
license-file = ["../LICENSE", "0"]
maintainer-scripts = "../pkg/debian/"
extended-description-file = "pkg/debian/description.txt"
depends = "$auto"
section = "database"
priority = "optional"
assets = [
  [
    "target/release/skyd",
    "usr/bin/",
    "755",
  ],
  [
    "target/release/skysh",
    "usr/bin/",
    "755",
  ],
  [
    "target/release/sky-bench",
    "usr/bin/",
    "755",
  ],
  [
    "../pkg/common/skyd.service",
    "/etc/systemd/system/skyd.service",
    "644",
  ],
]
