[package]
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
edition = "2021"
name = "sky-bench"
version = "0.8.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# internal deps
skytable = { git = "https://github.com/skytable/client-rust.git", branch = "octave" }
libstress = { path = "../libstress" }
