[package]
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
edition = "2021"
name = "sky-bench"
version = "0.8.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# internal deps
skytable = { git = "https://github.com/skytable/client-rust.git", features = [
    "sync",
    "dbg",
] }
libstress = { path = "../libstress" }
# external deps
clap = { version = "2", features = ["yaml"] }
log = "0.4.19"
env_logger = "0.10.0"
devtimer = "4.0.1"
serde = { version = "1.0.175", features = ["derive"] }
serde_json = "1.0.103"
rand = "0.8.5"
