[package]
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
edition = "2018"
name = "sky_macros"
version = "0.7.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
# external deps
proc-macro2 = "1.0.30"
quote = "1.0.10"
rand = "0.8.4"
syn = {version = "1.0.80", features = ["full"]}
