[package]
name = "corelib"
version = "0.3.2"
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
bytes = "0.5.6"

[features]
terrapipev2 =[]