on: [push, pull_request]

name: Test (arm64-native)

jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Test
        run: |
          source $HOME/.cargo/env
          make test
