on: [push, pull_request]

name: Test (arm64-native)

jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Test
        run: |
          make test
      - name: Stress test
        run: |
          make stress
